-- V6 Autopilot — Supabase pg_cron (volitelné, vyžaduje pg_cron + pg_net na Pro)
-- Primární plán: Vercel crons v vercel.json + Edge Functions v supabase/functions/*

-- Příklad (upravte URL a service role secret v Supabase Vault):
-- select cron.schedule(
--   'hourly_pubmed_monitor',
--   '0 * * * *',
--   $$ select net.http_get(
--     url := 'https://YOUR_PROJECT.supabase.co/functions/v1/pubmed-monitor',
--     headers := jsonb_build_object('Authorization', 'Bearer ' || current_setting('app.settings.service_role_key'))
--   ); $$
-- );
