/** Medical specialty categories for Supabase seed */
export const MEDICAL_CATEGORIES = [
  { name: "General Practice", slug: "general-practice", nameCs: "Všeobecné lékařství" },
  { name: "Internal Medicine", slug: "internal-medicine", nameCs: "Interna" },
  { name: "Cardiology", slug: "cardiology", nameCs: "Kardiologie" },
  { name: "Endocrinology / Diabetology", slug: "endocrinology", nameCs: "Endokrinologie / Diabetologie" },
  { name: "Rheumatology", slug: "rheumatology", nameCs: "Revmatologie" },
  { name: "Oncology", slug: "oncology", nameCs: "Onkologie" },
  { name: "Neurology", slug: "neurology", nameCs: "Neurologie" },
  { name: "Pulmonology", slug: "pulmonology", nameCs: "Pneumologie" },
  { name: "Dermatology", slug: "dermatology", nameCs: "Dermatologie" },
  { name: "Gastroenterology", slug: "gastroenterology", nameCs: "Gastroenterologie" },
  { name: "Infectious Disease", slug: "infectious-disease", nameCs: "Infekční medicína" },
  { name: "Psychiatry", slug: "psychiatry", nameCs: "Psychiatrie" },
  { name: "Allergy / Immunology", slug: "allergy-immunology", nameCs: "Alergologie / Imunologie" },
  { name: "Orthopedics", slug: "orthopedics", nameCs: "Ortopedie" },
  { name: "Surgery", slug: "surgery", nameCs: "Chirurgie" },
  { name: "Pediatrics", slug: "pediatrics", nameCs: "Pediatrie" },
  { name: "Emergency Medicine", slug: "emergency-medicine", nameCs: "Urgentní medicína" },
  { name: "Medical Education", slug: "medical-education", nameCs: "Studium medicíny" },
  { name: "Residents & Junior Doctors", slug: "residents", nameCs: "Mladí lékaři / rezidenti" },
  { name: "Ophthalmology", slug: "ophthalmology", nameCs: "Oční lékařství" },
  { name: "Glaucoma", slug: "glaucoma", nameCs: "Glaukom", parent: "ophthalmology" },
  { name: "Cataract", slug: "cataract", nameCs: "Katarakta", parent: "ophthalmology" },
  { name: "Macular Degeneration", slug: "macular-degeneration", nameCs: "Makulární degenerace", parent: "ophthalmology" },
  { name: "Diabetic Retinopathy", slug: "diabetic-retinopathy", nameCs: "Diabetická retinopatie", parent: "ophthalmology" },
  { name: "Refractive Disorders", slug: "refractive-disorders", nameCs: "Refrakční vady", parent: "ophthalmology" },
  { name: "Ocular Surgery", slug: "ocular-surgery", nameCs: "Oční chirurgie", parent: "ophthalmology" },
  { name: "Ocular Pharmacology", slug: "ocular-pharmacology", nameCs: "Oční farmakologie", parent: "ophthalmology" },
] as const;
