export const V25_HOME_HUBS = [
  {
    id: "verejnost",
    eyebrow: "Veřejnost",
    title: "Veřejné zdraví",
    description: "Prevence, výživa, spánek, stres a rozhovory s odborníky — srozumitelně v češtině.",
    href: "/verejnost",
    cta: "Prozkoumat veřejnost",
    links: ["Články", "Témata", "Rozhovory"],
  },
  {
    id: "studenti",
    eyebrow: "Studenti",
    title: "Studium medicíny",
    description: "Kvízy, studijní plány, přijímačky a přehled lékařských fakult v ČR.",
    href: "/studium",
    cta: "Studijní sekce",
    links: ["Kvízy", "Přijímačky", "LF"],
  },
  {
    id: "odbornici",
    eyebrow: "Odborníci",
    title: "Odborná sekce (ČLK)",
    description: "Obsah pro ověřené lékaře — algoritmy, farmakoterapie a směrnice po ověření ČLK.",
    href: "/odborna",
    cta: "Ověřit přístup",
    links: ["Algoritmy", "Směrnice", "Kazuistiky"],
  },
  {
    id: "clanky",
    eyebrow: "Magazín",
    title: "Odborné články",
    description: "Aktuální články s českým shrnutím pro praxi, výzkum a vzdělávání.",
    href: "/articles",
    cta: "Všechny články",
    links: ["Studie", "Novinky", "Briefy"],
  },
  {
    id: "leky",
    eyebrow: "Regulace",
    title: "Léky a registrace",
    description: "SÚKL, EMA, FDA — novinky, schválení a důležité informace o léčivých přípravcích.",
    href: "/leky",
    cta: "Sekce léky",
    links: ["SÚKL", "EMA", "Novinky"],
  },
] as const;
