import type { GlobalLocaleCode } from "@/lib/ecosystem/locales";
import type { SalesIcpSector } from "@/lib/sales/types";

/** locale, ISO country, company, website, sector, role local-part */
export type CampaignRawSeed = [GlobalLocaleCode, string, string, string, SalesIcpSector, string];

/**
 * Additional B2B firms: health software, medtech, health/psych services,
 * remote care platforms, beauty clinics. Role@official-domain only.
 */
export const CAMPAIGN_ROSTER_EXTRA: CampaignRawSeed[] = [
  ["cs", "CZ", "STAPRO", "https://www.stapro.cz", "digital_health", "obchod"],
  ["cs", "CZ", "Medicalc software", "https://www.medicalc.cz", "digital_health", "obchod"],
  ["cs", "CZ", "DS SOFT", "https://www.dssoft.cz", "digital_health", "info"],
  ["cs", "CZ", "LEKIS", "https://www.lekis.cz", "digital_health", "obchod"],
  ["cs", "CZ", "Magistra", "https://www.magistra.cz", "digital_health", "info"],
  ["cs", "CZ", "IZIP", "https://www.izip.cz", "digital_health", "info"],
  ["cs", "CZ", "MEDDI", "https://www.meddi.com", "digital_health", "info"],
  ["cs", "CZ", "Medevio", "https://www.medevio.cz", "digital_health", "info"],
  ["cs", "CZ", "ICZ", "https://www.icz.cz", "digital_health", "info"],
  ["cs", "CZ", "Asklepion", "https://www.asklepion.cz", "clinic", "info"],
  ["cs", "CZ", "YES VISAGE", "https://www.yesvisage.cz", "clinic", "info"],
  ["cs", "CZ", "Perfect Clinic", "https://www.perfectclinic.cz", "clinic", "info"],
  ["cs", "CZ", "Formé Clinic", "https://www.formeclinic.cz", "clinic", "info"],
  ["cs", "CZ", "Premier Clinic", "https://www.premierclinic.cz", "clinic", "info"],
  ["cs", "CZ", "Esthé", "https://www.esthe.cz", "clinic", "info"],
  ["cs", "CZ", "My Clinic Praha", "https://www.myclinic.cz", "clinic", "info"],
  ["cs", "CZ", "Fokus Praha", "https://www.fokus-praha.cz", "clinic", "info"],
  ["cs", "CZ", "NUDZ", "https://www.nudz.cz", "clinic", "info"],
  ["cs", "CZ", "Hedepy", "https://www.hedepy.cz", "digital_health", "info"],
  ["cs", "CZ", "Mindwell", "https://www.mindwell.cz", "digital_health", "info"],
  ["cs", "CZ", "Terapie.cz", "https://www.terapie.cz", "digital_health", "info"],
  ["cs", "CZ", "Anabell", "https://www.anabell.cz", "clinic", "info"],
  ["cs", "CZ", "Affidea Czech", "https://www.affidea.cz", "diagnostics", "info"],
  ["cs", "CZ", "GHC Clinic", "https://www.ghc.cz", "clinic", "info"],
  ["cs", "CZ", "Tescan", "https://www.tescan.com", "medtech", "info"],
  ["cs", "CZ", "Meopta", "https://www.meopta.com", "medtech", "info"],
  ["cs", "CZ", "Oncomed", "https://www.oncomed.cz", "clinic", "info"],
  ["cs", "CZ", "Moje Ambulance", "https://www.mojeambulance.cz", "clinic", "info"],
  ["cs", "CZ", "Program Health Plus", "https://www.programhealthplus.cz", "clinic", "info"],
  ["cs", "CZ", "Canadian Medical already skip", "https://skip.invalid", "clinic", "info"],
  ["sk", "SK", "eHealth Slovakia vendor Asseco", "https://www.asseco.com", "digital_health", "info"],
  ["sk", "SK", "Medical Systems SK", "https://www.medicalsystems.sk", "digital_health", "info"],
  ["sk", "SK", "ProCare Digital", "https://www.procare.sk", "clinic", "marketing"],
  ["sk", "SK", "Asklepios Slovakia", "https://www.asklepios.sk", "clinic", "info"],
  ["sk", "SK", "Esthetic clinic Bratislava", "https://www.borovicova.sk", "clinic", "info"],
  ["sk", "SK", "Iscare Slovakia", "https://www.iscare.sk", "clinic", "info"],
  ["sk", "SK", "Psychoprof", "https://www.psychoprof.sk", "clinic", "info"],
  ["sk", "SK", "Telemedicína SK uLékaře", "https://www.ulekare.sk", "digital_health", "info"],
  ["sk", "SK", "Dr.Digital SK", "https://www.ehealth.sk", "digital_health", "info"],
  ["sk", "SK", "Omega Clinic", "https://www.omegaclinic.sk", "clinic", "info"],
  ["sk", "SK", "Boramed", "https://www.boramed.sk", "medtech", "info"],
  ["sk", "SK", "Chirana", "https://www.chirana.eu", "medtech", "info"],
  ["sk", "SK", "Medical Group SK", "https://www.medicalgroup.sk", "clinic", "info"],
  ["sk", "SK", "Nemocnica Bory", "https://www.nemocnicabory.sk", "clinic", "info"],
  ["sk", "SK", "Unilabs already skip", "https://skip.invalid", "lab", "info"],
  ["pl", "PL", "Comarch Healthcare", "https://www.comarch.com", "digital_health", "info"],
  ["pl", "PL", "Asseco Poland Health", "https://pl.asseco.com", "digital_health", "info"],
  ["pl", "PL", "Kamsoft", "https://www.kamsoft.pl", "digital_health", "info"],
  ["pl", "PL", "KS-AOW", "https://www.ks-aow.pl", "digital_health", "info"],
  ["pl", "PL", "Medfile", "https://www.medfile.pl", "digital_health", "info"],
  ["pl", "PL", "ZnanyLekarz", "https://www.znanylekarz.pl", "digital_health", "press"],
  ["pl", "PL", "Telemedi", "https://telemedi.co", "digital_health", "info"],
  ["pl", "PL", "Infermedica", "https://infermedica.com", "digital_health", "info"],
  ["pl", "PL", "StethoMe", "https://stethome.com", "medtech", "info"],
  ["pl", "PL", "Lifeclinic", "https://www.lifeclinic.pl", "clinic", "info"],
  ["pl", "PL", "Carolina Medical Center", "https://www.carolina.pl", "clinic", "info"],
  ["pl", "PL", "Klinika Bocian", "https://www.klinikabocian.pl", "clinic", "info"],
  ["pl", "PL", "Estheticon Poland", "https://www.estheticon.com", "clinic", "info"],
  ["pl", "PL", "Damian Medical Center", "https://www.damian.pl", "clinic", "info"],
  ["pl", "PL", "Mind Health PL", "https://mindhealth.pl", "clinic", "info"],
  ["de", "DE", "CompuGroup Medical", "https://www.cgm.com", "digital_health", "info"],
  ["de", "DE", "Nexus AG", "https://www.nexus-ag.de", "digital_health", "info"],
  ["de", "DE", "Dedalus", "https://www.dedalus.com", "digital_health", "info"],
  ["de", "DE", "TeleClinic", "https://www.teleclinic.com", "digital_health", "press"],
  ["de", "DE", "Ada Health", "https://ada.com", "digital_health", "press"],
  ["de", "DE", "Curalie", "https://www.curalie.com", "digital_health", "info"],
  ["de", "DE", "Medgate Germany", "https://www.medgate.de", "digital_health", "info"],
  ["de", "DE", "Doctolib Germany", "https://www.doctolib.de", "digital_health", "press"],
  ["de", "DE", "Schön Klinik", "https://www.schoen-klinik.de", "clinic", "info"],
  ["de", "DE", "Mediclin", "https://www.mediclin.de", "clinic", "info"],
  ["de", "DE", "Artemed", "https://www.artemed.de", "clinic", "info"],
  ["de", "DE", "Privatklinikgruppe", "https://www.atos-kliniken.com", "clinic", "info"],
  ["de", "DE", "Klinik am Ring", "https://www.klinik-am-ring.de", "clinic", "info"],
  ["de", "DE", "Merz Aesthetics", "https://www.merz.com", "medtech", "info"],
  ["de", "DE", "Brainlab", "https://www.brainlab.com", "medtech", "info"],
  ["de", "DE", "Karl Storz", "https://www.karlstorz.com", "medtech", "info"],
  ["de", "DE", "Paul Hartmann", "https://www.hartmann.info", "medtech", "media"],
  ["de", "DE", "MindDoc", "https://www.minddoc.com", "digital_health", "info"],
  ["de", "DE", "Selfapy", "https://www.selfapy.com", "digital_health", "info"],
  ["fr", "FR", "Cegedim", "https://www.cegedim.com", "digital_health", "info"],
  ["fr", "FR", "Maincare", "https://www.maincare.com", "digital_health", "info"],
  ["fr", "FR", "Qare", "https://www.qare.fr", "digital_health", "press"],
  ["fr", "FR", "Alan", "https://alan.com", "insurance", "press"],
  ["fr", "FR", "Withings", "https://www.withings.com", "medtech", "press"],
  ["fr", "FR", "BioSerenity", "https://www.bioserenity.com", "medtech", "info"],
  ["fr", "FR", "Doctolib already skip", "https://skip.invalid", "digital_health", "press"],
  ["fr", "FR", "Clinique des Champs-Élysées", "https://www.cliniquechampselysees.com", "clinic", "info"],
  ["fr", "FR", "Groupe Elsan already skip", "https://skip.invalid", "clinic", "info"],
  ["fr", "FR", "Clinique du Louvre", "https://www.cliniquedulouvre.com", "clinic", "info"],
  ["fr", "FR", "Qare psych", "https://www.qare.fr", "digital_health", "contact"],
  ["fr", "FR", "HypnoVR", "https://hypnovr.io", "digital_health", "info"],
  ["fr", "FR", "Owkin", "https://www.owkin.com", "digital_health", "press"],
  ["fr", "FR", "Guerbet", "https://www.guerbet.com", "diagnostics", "info"],
  ["fr", "FR", "Evolucare", "https://www.evolucare.com", "digital_health", "info"],
  ["it", "IT", "Dedalus Italia", "https://www.dedalus.com", "digital_health", "contact"],
  ["it", "IT", "Engineering Healthcare", "https://www.eng.it", "digital_health", "info"],
  ["it", "IT", "Paginemediche", "https://www.paginemediche.it", "digital_health", "info"],
  ["it", "IT", "MioDottore", "https://www.miodottore.it", "digital_health", "press"],
  ["it", "IT", "Tecnologie Sanitarie", "https://www.tecnologiesanitarie.it", "medtech", "info"],
  ["it", "IT", "Esaote", "https://www.esaote.com", "medtech", "info"],
  ["it", "IT", "Sorin already skip", "https://skip.invalid", "medtech", "info"],
  ["it", "IT", "Istituto Europeo di Oncologia", "https://www.ieo.it", "clinic", "info"],
  ["it", "IT", "Campus Bio-Medico", "https://www.unicampus.it", "clinic", "info"],
  ["it", "IT", "Villa Stuart", "https://www.villastuart.it", "clinic", "info"],
  ["it", "IT", "UPMC Italy", "https://www.upmc.it", "clinic", "info"],
  ["it", "IT", "Serenis", "https://www.serenis.it", "digital_health", "info"],
  ["it", "IT", "Unobravo", "https://www.unobravo.com", "digital_health", "info"],
  ["it", "IT", "Bioscience Institute", "https://www.bioinst.com", "clinic", "info"],
  ["es", "ES", "Savia / Mapfre Digital", "https://www.savia.net", "digital_health", "info"],
  ["es", "ES", "Doctoralia", "https://www.doctoralia.es", "digital_health", "press"],
  ["es", "ES", "Mediktor", "https://www.mediktor.com", "digital_health", "info"],
  ["es", "ES", "Iomed", "https://www.iomed.health", "digital_health", "info"],
  ["es", "ES", "Idoven", "https://www.idoven.ai", "digital_health", "info"],
  ["es", "ES", "Devicare", "https://www.devicare.com", "medtech", "info"],
  ["es", "ES", "Atrys Health", "https://www.atryshealth.com", "clinic", "info"],
  ["es", "ES", "IMQ", "https://www.imq.es", "clinic", "info"],
  ["es", "ES", "Clínica Universidad de Navarra", "https://www.cun.es", "clinic", "info"],
  ["es", "ES", "Hospital El Pilar", "https://www.quironsalud.es", "clinic", "press"],
  ["es", "ES", "Clínica Planas", "https://www.clinicaplanas.com", "clinic", "info"],
  ["es", "ES", "Instituto Médico Láser", "https://www.iml.es", "clinic", "info"],
  ["es", "ES", "ifeel", "https://ifeelonline.com", "digital_health", "info"],
  ["es", "ES", "TherapyChat", "https://www.therapychat.com", "digital_health", "info"],
  ["pt", "PT", "Glintt", "https://www.glintt.com", "digital_health", "info"],
  ["pt", "PT", "Alert Life Sciences", "https://www.alert-online.com", "digital_health", "info"],
  ["pt", "PT", "Médicos na Net", "https://www.medicosnanet.pt", "digital_health", "info"],
  ["pt", "PT", "Teladoc Portugal", "https://www.teladochealth.com", "digital_health", "contact"],
  ["pt", "PT", "Hospital da Luz", "https://www.hospitaldaluz.pt", "clinic", "info"],
  ["pt", "PT", "Trofa Saúde", "https://www.trofasaude.pt", "clinic", "info"],
  ["pt", "PT", "Lusiadas already skip", "https://skip.invalid", "clinic", "info"],
  ["pt", "PT", "Clínica do Tempo", "https://www.clinicadotempo.pt", "clinic", "info"],
  ["pt", "PT", "Grupo HPA Saúde", "https://www.grupohpa.com", "clinic", "info"],
  ["pt", "PT", "PsiCare", "https://www.psicare.pt", "clinic", "info"],
  ["pt", "PT", "Mindclinic PT", "https://www.mind.pt", "clinic", "info"],
  ["pt-BR", "BR", "MV Sistemas", "https://www.mv.com.br", "digital_health", "info"],
  ["pt-BR", "BR", "Philips Tasy", "https://www.philips.com.br", "digital_health", "info"],
  ["pt-BR", "BR", "Conexa Saúde", "https://www.conexasaude.com.br", "digital_health", "info"],
  ["pt-BR", "BR", "Dr.Consulta", "https://www.drconsulta.com", "clinic", "info"],
  ["pt-BR", "BR", "Alice", "https://www.alice.com.br", "clinic", "press"],
  ["pt-BR", "BR", "Rede D'Or", "https://www.rededor.com.br", "clinic", "info"],
  ["pt-BR", "BR", "Hospital Moinhos de Vento", "https://www.hospitalmoinhos.org.br", "clinic", "info"],
  ["pt-BR", "BR", "Oswaldo Cruz", "https://www.hospitaloswaldocruz.org.br", "clinic", "info"],
  ["pt-BR", "BR", "Vita Dermatologia", "https://www.vitadermatologia.com.br", "clinic", "info"],
  ["pt-BR", "BR", "Zenklub", "https://zenklub.com.br", "digital_health", "info"],
  ["pt-BR", "BR", "Vittude", "https://www.vittude.com", "digital_health", "info"],
  ["pt-BR", "BR", "Afya", "https://www.afya.com.br", "education", "info"],
  ["pt-BR", "BR", "Memed", "https://memed.com.br", "digital_health", "info"],
  ["ro", "RO", "SIVECO Healthcare", "https://www.siveco.ro", "digital_health", "info"],
  ["ro", "RO", "SoftTehnica Medical", "https://www.soft-tehnica.com", "digital_health", "info"],
  ["ro", "RO", "DocBook", "https://www.docbook.ro", "digital_health", "info"],
  ["ro", "RO", "Regina Maria Digital", "https://www.reginamaria.ro", "clinic", "press"],
  ["ro", "RO", "MedLife Digital", "https://www.medlife.ro", "clinic", "press"],
  ["ro", "RO", "Sanador already skip", "https://skip.invalid", "clinic", "info"],
  ["ro", "RO", "Medicover Romania", "https://www.medicover.ro", "clinic", "info"],
  ["ro", "RO", "Affidea Romania", "https://www.affidea.ro", "diagnostics", "info"],
  ["ro", "RO", "Monza Hospital", "https://www.spitalulmonza.ro", "clinic", "info"],
  ["ro", "RO", "Clinicco", "https://www.clinicco.ro", "clinic", "info"],
  ["ro", "RO", "Ana Medical Center", "https://www.anamedical.ro", "clinic", "info"],
  ["ro", "RO", "MindCare RO", "https://www.mindcare.ro", "clinic", "info"],
  ["hu", "HU", "T-Systems Hungary Health", "https://www.t-systems.hu", "digital_health", "info"],
  ["hu", "HU", "eMedsol", "https://www.emedsol.hu", "digital_health", "info"],
  ["hu", "HU", "Doktor24", "https://www.doktor24.hu", "clinic", "info"],
  ["hu", "HU", "TritonLife", "https://www.tritonlife.hu", "clinic", "info"],
  ["hu", "HU", "Budai Egészségközpont", "https://www.bhc.hu", "clinic", "info"],
  ["hu", "HU", "Dr. Rose Private Hospital", "https://www.drrose.hu", "clinic", "info"],
  ["hu", "HU", "FirstMed", "https://www.firstmedcenters.com", "clinic", "info"],
  ["hu", "HU", "Róbert Károly Magánkórház", "https://www.robertkorhaz.hu", "clinic", "info"],
  ["hu", "HU", "New Age Medical", "https://www.newagemedical.hu", "clinic", "info"],
  ["hu", "HU", "Mindset Psychology", "https://www.mindset.co.hu", "clinic", "info"],
  ["hu", "HU", "77 Elektronika", "https://www.e77.hu", "medtech", "info"],
  ["ru", "RU", "СберЗдоровье", "https://sberhealth.ru", "digital_health", "info"],
  ["ru", "RU", "Яндекс Здоровье", "https://health.yandex.ru", "digital_health", "info"],
  ["ru", "RU", "DocDoc", "https://docdoc.ru", "digital_health", "info"],
  ["ru", "RU", "СМ-Клиника", "https://www.smclinic.ru", "clinic", "info"],
  ["ru", "RU", "Медси already skip", "https://skip.invalid", "clinic", "info"],
  ["ru", "RU", "Будь Здоров", "https://www.budzdorov.ru", "clinic", "info"],
  ["ru", "RU", "Hadassah Medical Moscow", "https://www.hadassah.moscow", "clinic", "info"],
  ["ru", "RU", "Клиника Рассвет", "https://klinikarassvet.ru", "clinic", "info"],
  ["ru", "RU", "Alter", "https://alter.ru", "digital_health", "info"],
  ["ru", "RU", "Zigmund.Online", "https://zigmund.online", "digital_health", "info"],
  ["ru", "RU", "НМИЦ им. Алмазова", "https://www.almazovcentre.ru", "clinic", "info"],
  ["uk", "UA", "Helsi", "https://helsi.me", "digital_health", "info"],
  ["uk", "UA", "Doc.ua", "https://doc.ua", "digital_health", "info"],
  ["uk", "UA", "Liki24", "https://liki24.com", "pharmacy", "info"],
  ["uk", "UA", "Into-Sana", "https://into-sana.ua", "clinic", "info"],
  ["uk", "UA", "Oberig", "https://oberig.ua", "clinic", "info"],
  ["uk", "UA", "Adonis", "https://adonis-clinic.com", "clinic", "info"],
  ["uk", "UA", "Dobrobut already skip", "https://skip.invalid", "clinic", "info"],
  ["uk", "UA", "Leleka", "https://leleka.com.ua", "clinic", "info"],
  ["uk", "UA", "Isida", "https://isida.ua", "clinic", "info"],
  ["uk", "UA", "Psychea", "https://psychea.com.ua", "clinic", "info"],
  ["be", "BY", "TUT.BY Health skip", "https://skip.invalid", "digital_health", "info"],
  ["be", "BY", "Мой Доктор BY", "https://www.emsch.by", "clinic", "info"],
  ["be", "BY", "Лодэ", "https://lode.by", "clinic", "info"],
  ["be", "BY", "Экомедсервис", "https://ecomed.by", "clinic", "info"],
  ["be", "BY", "Кравцов клиника", "https://kravtsov.by", "clinic", "info"],
  ["be", "BY", "Nordin", "https://nordin.by", "clinic", "info"],
  ["zh-CN", "CN", "WeDoctor", "https://www.guahao.com", "digital_health", "info"],
  ["zh-CN", "CN", "JD Health", "https://www.jdh.com", "digital_health", "info"],
  ["zh-CN", "CN", "Tencent Healthcare", "https://www.tencent.com", "digital_health", "press"],
  ["zh-CN", "CN", "Neusoft Medical", "https://www.neusoftmedical.com", "medtech", "info"],
  ["zh-CN", "CN", "United Imaging already skip", "https://skip.invalid", "medtech", "info"],
  ["zh-CN", "CN", "Wego", "https://www.wego.com.cn", "medtech", "info"],
  ["zh-CN", "CN", "Aier Eye Hospital", "https://www.aierchina.com", "clinic", "info"],
  ["zh-CN", "CN", "Jiahui Health", "https://www.jiahui.com", "clinic", "info"],
  ["zh-CN", "CN", "Parkway Shanghai", "https://www.parkwayhealth.cn", "clinic", "info"],
  ["zh-CN", "CN", "Yidu Tech", "https://www.yidutech.com", "digital_health", "info"],
  ["ja", "JP", "M3", "https://corporate.m3.com", "digital_health", "info"],
  ["ja", "JP", "Medley", "https://www.medley.jp", "digital_health", "info"],
  ["ja", "JP", "EM Systems", "https://www.emsystems.co.jp", "digital_health", "info"],
  ["ja", "JP", "Fujitsu Healthcare", "https://www.fujitsu.com", "digital_health", "press"],
  ["ja", "JP", "Olympus already skip", "https://skip.invalid", "medtech", "info"],
  ["ja", "JP", "Nihon Kohden already skip", "https://skip.invalid", "medtech", "info"],
  ["ja", "JP", "St. Luke's International Hospital", "https://hospital.luke.ac.jp", "clinic", "info"],
  ["ja", "JP", "Tokyo Midtown Clinic", "https://www.tokyomidtown-mc.jp", "clinic", "info"],
  ["ja", "JP", "AOI International Hospital", "https://www.aoikai.jp", "clinic", "info"],
  ["ja", "JP", "T-PEC", "https://www.t-pec.co.jp", "clinic", "info"],
  ["ja", "JP", "BetterHelp Japan skip", "https://skip.invalid", "digital_health", "info"],
  ["ko", "KR", "Kakao Healthcare", "https://www.kakaocorp.com", "digital_health", "press"],
  ["ko", "KR", "Naver Healthcare", "https://www.navercorp.com", "digital_health", "press"],
  ["ko", "KR", "VUNO already skip", "https://skip.invalid", "digital_health", "info"],
  ["ko", "KR", "Lunit already skip", "https://skip.invalid", "digital_health", "info"],
  ["ko", "KR", "Seoul National University Hospital", "https://www.snuh.org", "clinic", "info"],
  ["ko", "KR", "Samsung Medical Center", "https://www.samsunghospital.com", "clinic", "info"],
  ["ko", "KR", "Asan Medical Center", "https://www.amc.seoul.kr", "clinic", "info"],
  ["ko", "KR", "JK Plastic Surgery", "https://www.jkplastic.com", "clinic", "info"],
  ["ko", "KR", "Banobagi", "https://www.banobagi.com", "clinic", "info"],
  ["ko", "KR", "ID Hospital", "https://www.idhospital.com", "clinic", "info"],
  ["vi", "VN", "Viettel Healthcare", "https://www.viettel.com.vn", "digital_health", "info"],
  ["vi", "VN", "FPT Healthcare", "https://www.fpt.com.vn", "digital_health", "info"],
  ["vi", "VN", "Jio Health", "https://www.jiohealth.com", "digital_health", "info"],
  ["vi", "VN", "eDoctor", "https://edoctor.io", "digital_health", "info"],
  ["vi", "VN", "Vinmec already skip", "https://skip.invalid", "clinic", "info"],
  ["vi", "VN", "Tam Anh Hospital", "https://tamanhhospital.vn", "clinic", "info"],
  ["vi", "VN", "Thu Cuc", "https://www.thucuchospital.vn", "clinic", "info"],
  ["vi", "VN", "Kangnam Clinic VN", "https://benhvienthammykangnam.vn", "clinic", "info"],
  ["vi", "VN", "YouMed", "https://youmed.vn", "digital_health", "info"],
  ["id", "ID", "AloDokter", "https://www.alodokter.com", "digital_health", "info"],
  ["id", "ID", "Halodoc already skip", "https://skip.invalid", "digital_health", "info"],
  ["id", "ID", "KlikDokter", "https://www.klikdokter.com", "digital_health", "info"],
  ["id", "ID", "Good Doctor ID", "https://gooddoctor.co.id", "digital_health", "info"],
  ["id", "ID", "Siloam already skip", "https://skip.invalid", "clinic", "info"],
  ["id", "ID", "Mayapada Hospital", "https://www.mayapadahospital.com", "clinic", "info"],
  ["id", "ID", "Pondok Indah Hospital", "https://www.rspondokindah.co.id", "clinic", "info"],
  ["id", "ID", "ERHA Clinic", "https://www.erha.co.id", "clinic", "info"],
  ["id", "ID", "ZAP Clinic", "https://zap.co.id", "clinic", "info"],
  ["en", "INT", "Epic Systems", "https://www.epic.com", "digital_health", "info"],
  ["en", "INT", "Oracle Health", "https://www.oracle.com", "digital_health", "info"],
  ["en", "INT", "InterSystems", "https://www.intersystems.com", "digital_health", "info"],
  ["en", "INT", "Veeva Systems", "https://www.veeva.com", "digital_health", "info"],
  ["en", "INT", "Amwell", "https://business.amwell.com", "digital_health", "info"],
  ["en", "INT", "Doximity", "https://www.doximity.com", "digital_health", "press"],
  ["en", "INT", "Intuitive Surgical", "https://www.intuitive.com", "medtech", "info"],
  ["en", "INT", "Edwards Lifesciences", "https://www.edwards.com", "medtech", "info"],
  ["en", "INT", "ResMed", "https://www.resmed.com", "medtech", "info"],
  ["en", "INT", "Hologic", "https://www.hologic.com", "diagnostics", "info"],
  ["en", "INT", "Bio-Rad", "https://www.bio-rad.com", "diagnostics", "info"],
  ["en", "INT", "Qiagen", "https://www.qiagen.com", "diagnostics", "info"],
  ["en", "INT", "Galderma", "https://www.galderma.com", "medtech", "info"],
  ["en", "INT", "Allergan Aesthetics", "https://www.allerganaesthetics.com", "medtech", "info"],
  ["en", "INT", "Cutera", "https://cutera.com", "medtech", "info"],
  ["en", "INT", "Candela Medical", "https://candelamedical.com", "medtech", "info"],
  ["en", "INT", "Lumenis", "https://lumenis.com", "medtech", "info"],
  ["en", "INT", "InMode", "https://inmodemd.com", "medtech", "info"],
  ["en", "INT", "Fotona", "https://www.fotona.com", "medtech", "info"],
  ["en", "INT", "Cynosure", "https://www.cynosure.com", "medtech", "info"],
  ["en", "INT", "Lyra Health", "https://www.lyrahealth.com", "digital_health", "info"],
  ["en", "INT", "Spring Health", "https://www.springhealth.com", "digital_health", "info"],
  ["en", "INT", "Talkspace", "https://www.talkspace.com", "digital_health", "press"],
  ["en", "INT", "BetterHelp", "https://www.betterhelp.com", "digital_health", "press"],
  ["en-US", "US", "Epic already skip", "https://skip.invalid", "digital_health", "info"],
  ["en-US", "US", "Veradigm", "https://www.veradigm.com", "digital_health", "info"],
  ["en-US", "US", "athenahealth", "https://www.athenahealth.com", "digital_health", "info"],
  ["en-US", "US", "eClinicalWorks", "https://www.eclinicalworks.com", "digital_health", "info"],
  ["en-US", "US", "NextGen Healthcare", "https://www.nextgen.com", "digital_health", "info"],
  ["en-US", "US", "Teladoc already skip", "https://skip.invalid", "digital_health", "media"],
  ["en-US", "US", "Included Health", "https://includedhealth.com", "digital_health", "info"],
  ["en-US", "US", "Ro", "https://ro.co", "digital_health", "press"],
  ["en-US", "US", "Hims & Hers", "https://www.hims.com", "digital_health", "press"],
  ["en-US", "US", "Cleveland Clinic", "https://my.clevelandclinic.org", "clinic", "info"],
  ["en-US", "US", "Mayo Clinic", "https://www.mayoclinic.org", "clinic", "info"],
  ["en-US", "US", "Johns Hopkins Medicine", "https://www.hopkinsmedicine.org", "clinic", "info"],
  ["en-US", "US", "Kaiser Permanente", "https://www.kaiserpermanente.org", "clinic", "info"],
  ["en-US", "US", "Mass General Brigham", "https://www.massgeneralbrigham.org", "clinic", "info"],
  ["en-US", "US", "NYU Langone", "https://nyulangone.org", "clinic", "info"],
  ["en-US", "US", "Cedars-Sinai", "https://www.cedars-sinai.org", "clinic", "info"],
  ["en-US", "US", "MD Anderson", "https://www.mdanderson.org", "clinic", "info"],
  ["en-US", "US", "Allergan already skip", "https://skip.invalid", "medtech", "info"],
  ["en-US", "US", "SkinCeuticals", "https://www.skinceuticals.com", "clinic", "info"],
  ["en-US", "US", "Ideal Image", "https://www.idealimage.com", "clinic", "info"],
  ["en-US", "US", "LaserAway", "https://www.laseraway.com", "clinic", "info"],
  ["en-UK", "GB", "EMIS Health", "https://www.emishealth.com", "digital_health", "info"],
  ["en-UK", "GB", "TPP SystmOne", "https://www.tpp-uk.com", "digital_health", "info"],
  ["en-UK", "GB", "Babylon skip", "https://skip.invalid", "digital_health", "info"],
  ["en-UK", "GB", "Livi / Kry", "https://www.livi.co.uk", "digital_health", "press"],
  ["en-UK", "GB", "Push Doctor", "https://www.pushdoctor.co.uk", "digital_health", "info"],
  ["en-UK", "GB", "Zava", "https://www.zavamed.com", "digital_health", "info"],
  ["en-UK", "GB", "HCA UK", "https://www.hcahealthcare.co.uk", "clinic", "info"],
  ["en-UK", "GB", "Cleveland Clinic London", "https://clevelandcliniclondon.uk", "clinic", "info"],
  ["en-UK", "GB", "The Harley Medical Group", "https://www.harleymedical.co.uk", "clinic", "info"],
  ["en-UK", "GB", "Cadogan Clinic", "https://www.cadoganclinic.com", "clinic", "info"],
  ["en-UK", "GB", "The London Clinic", "https://www.thelondonclinic.co.uk", "clinic", "info"],
  ["en-UK", "GB", "Circle Health Group", "https://www.circlehealthgroup.co.uk", "clinic", "info"],
  ["en-UK", "GB", "Priory Group", "https://www.priorygroup.com", "clinic", "info"],
  ["en-UK", "GB", "Nightingale Hospital", "https://www.nightingalehospital.co.uk", "clinic", "info"],
  ["en-UK", "GB", "Ieso Digital Health", "https://www.iesohealth.com", "digital_health", "info"],
  ["en", "INT", "Align Technology", "https://www.aligntech.com", "medtech", "info"],
  ["en", "INT", "Dentsply Sirona", "https://www.dentsplysirona.com", "medtech", "info"],
  ["en", "INT", "Straumann", "https://www.straumann.com", "medtech", "info"],
  ["en", "INT", "Nobel Biocare", "https://www.nobelbiocare.com", "medtech", "info"],
  ["en", "INT", "Planmeca", "https://www.planmeca.com", "medtech", "info"],
  ["en", "INT", "3Shape", "https://www.3shape.com", "medtech", "info"],
  ["en", "INT", "Coloplast", "https://www.coloplast.com", "medtech", "info"],
  ["en", "INT", "Mölnlycke", "https://www.molnlycke.com", "medtech", "info"],
  ["en", "INT", "Essity", "https://www.essity.com", "medtech", "info"],
  ["en", "INT", "Kenvue", "https://www.kenvue.com", "pharma_otc", "media"],
  ["en", "INT", "Organon", "https://www.organon.com", "pharma_rx", "media"],
  ["en", "INT", "Viatris", "https://www.viatris.com", "pharma_rx", "media"],
  ["en", "INT", "Sandoz", "https://www.sandoz.com", "pharma_rx", "media"],
  ["en", "INT", "Moderna", "https://www.modernatx.com", "pharma_rx", "media"],
  ["en", "INT", "BioNTech", "https://www.biontech.com", "pharma_rx", "media"],
  ["en", "INT", "Gilead", "https://www.gilead.com", "pharma_rx", "media"],
  ["en", "INT", "Amgen", "https://www.amgen.com", "pharma_rx", "media"],
  ["en", "INT", "Regeneron", "https://www.regeneron.com", "pharma_rx", "media"],
  ["en", "INT", "Agilent", "https://www.agilent.com", "diagnostics", "info"],
  ["en", "INT", "Revvity", "https://www.revvity.com", "diagnostics", "info"],
  ["en", "INT", "Sartorius", "https://www.sartorius.com", "medtech", "info"],
  ["en", "INT", "Eppendorf", "https://www.eppendorf.com", "medtech", "info"],
  ["en", "INT", "Canon Medical", "https://global.medical.canon", "medtech", "info"],
  ["en", "INT", "Carestream", "https://www.carestream.com", "medtech", "info"],
  ["en", "INT", "Cook Medical", "https://www.cookmedical.com", "medtech", "info"],
  ["en", "INT", "Teleflex", "https://www.teleflex.com", "medtech", "info"],
  ["en", "INT", "ICU Medical", "https://www.icumed.com", "medtech", "info"],
  ["en", "INT", "DaVita", "https://www.davita.com", "clinic", "info"],
  ["en", "INT", "Fresenius Medical Care", "https://www.freseniusmedicalcare.com", "clinic", "info"],
  ["en", "INT", "Johnson & Johnson MedTech", "https://www.jnj.com", "medtech", "info"],
  ["en", "INT", "Roche Group", "https://www.roche.com", "diagnostics", "media"],
  ["en", "INT", "Novartis Group", "https://www.novartis.com", "pharma_rx", "media"],
  ["en", "INT", "Bayer", "https://www.bayer.com", "pharma_otc", "media"],
  ["en", "INT", "Merck KGaA", "https://www.merckgroup.com", "pharma_rx", "media"],
  ["en", "INT", "L'Oréal Dermatological Beauty", "https://www.loreal.com", "clinic", "press"],
  ["en", "INT", "Beiersdorf", "https://www.beiersdorf.com", "pharma_otc", "press"],
  ["en", "INT", "Reckitt", "https://www.reckitt.com", "pharma_otc", "press"],
  ["en-US", "US", "MEDITECH", "https://ehr.meditech.com", "digital_health", "info"],
  ["en-US", "US", "ModMed", "https://www.modmed.com", "digital_health", "info"],
  ["en-US", "US", "Nextech", "https://www.nextech.com", "digital_health", "info"],
  ["en-US", "US", "SimplePractice", "https://www.simplepractice.com", "digital_health", "info"],
  ["en-US", "US", "Tebra", "https://www.tebra.com", "digital_health", "info"],
  ["en-US", "US", "Zenoti", "https://www.zenoti.com", "digital_health", "info"],
  ["en-US", "US", "Phorest", "https://www.phorest.com", "digital_health", "info"],
  ["en-US", "US", "Cerebral", "https://cerebral.com", "digital_health", "press"],
  ["en-US", "US", "Headway", "https://headway.co", "digital_health", "info"],
  ["en-US", "US", "Alma", "https://helloalma.com", "digital_health", "info"],
  ["en-US", "US", "Rula", "https://www.rula.com", "digital_health", "info"],
  ["en-US", "US", "Grow Therapy", "https://growtherapy.com", "digital_health", "info"],
  ["en-US", "US", "Brightside", "https://www.brightside.com", "digital_health", "info"],
  ["en-US", "US", "Headspace Health", "https://www.headspace.com", "digital_health", "press"],
  ["en-US", "US", "Calm", "https://www.calm.com", "digital_health", "press"],
  ["en-UK", "GB", "Accurx", "https://www.accurx.com", "digital_health", "info"],
  ["en-UK", "GB", "eConsult", "https://econsult.net", "digital_health", "info"],
  ["en-UK", "GB", "Kry", "https://www.kry.se", "digital_health", "press"],
  ["en-UK", "GB", "HealthHero", "https://www.healthhero.com", "digital_health", "info"],
  ["en-UK", "GB", "Togetherall", "https://togetherall.com", "digital_health", "info"],
  ["en-UK", "GB", "SilverCloud", "https://www.silvercloudhealth.com", "digital_health", "info"],
  ["cs", "CZ", "ABClinic Art & Beauty", "https://www.abclinic.cz", "clinic", "info"],
  ["cs", "CZ", "GIA Clinic", "https://www.gia.cz", "clinic", "info"],
  ["cs", "CZ", "Altos Clinic", "https://www.altos.cz", "clinic", "info"],
  ["cs", "CZ", "Body Clinic Praha", "https://www.bodyclinic.cz", "clinic", "info"],
  ["cs", "CZ", "Adicare", "https://www.adicare.cz", "clinic", "info"],
  ["cs", "CZ", "Psychosom", "https://www.psychosom.cz", "clinic", "info"],
  ["cs", "CZ", "Relief SAS", "https://www.relief.cz", "clinic", "info"],
  ["cs", "CZ", "eRecept vendor SÚKL skip", "https://skip.invalid", "digital_health", "info"],
  ["cs", "CZ", "CompuGroup Medical ČR", "https://www.cgm.com/cz", "digital_health", "info"],
  ["de", "DE", "ID GmbH & Co. KGaA", "https://www.id-berlin.de", "digital_health", "info"],
  ["de", "DE", "Medatixx", "https://www.medatixx.de", "digital_health", "info"],
  ["de", "DE", "TurboMed", "https://www.turbomed.de", "digital_health", "info"],
  ["de", "DE", "T2med", "https://www.t2med.de", "digital_health", "info"],
  ["de", "DE", "MediaDok", "https://www.mediadok.de", "digital_health", "info"],
  ["fr", "FR", "Cegedim Santé", "https://www.cegedimsante.com", "digital_health", "info"],
  ["fr", "FR", "Weda", "https://weda.fr", "digital_health", "info"],
  ["it", "IT", "Dedalus skip dup", "https://skip.invalid", "digital_health", "info"],
  ["it", "IT", "GPI", "https://www.gpigroup.com", "digital_health", "info"],
  ["pl", "PL", "Comarch already skip", "https://skip.invalid", "digital_health", "info"],
  ["pl", "PL", "Gabinet.gov skip", "https://skip.invalid", "digital_health", "info"],
  ["pl", "PL", "Enel-Med Digital", "https://www.enel.pl", "clinic", "press"],
];
