import type { Metadata } from "next";
import Link from "next/link";
import { cookies } from "next/headers";
import { ArticleFilter } from "@/components/article-filter";
import { articleAccessCookieName, readArticleAccessCookie, resolveArticleAccess } from "@/lib/article-access";
import { audienceLabels, dailyArticleTarget, specializations } from "@/lib/data";
import { filterArticles, parseArticleFilters } from "@/lib/content";
type SearchParams = Promise<Record<string, string | string[] | undefined>>;
export const metadata: Metadata = { title: "Články", description: "Ověřené medicínské články s autorem, datem a zdrojem." };
export const dynamic = "force-dynamic";
export default async function ArticlesPage({ searchParams }: { searchParams: SearchParams }) { const filters = parseArticleFilters(await searchParams); const results = filterArticles(filters); const cookieStore = await cookies(); const profile = readArticleAccessCookie(cookieStore.get(articleAccessCookieName)?.value); return <main className="section"><p className="eyebrow">Články a novinky</p><h1>Medicínské poznatky podle specializace.</h1><p className="lead">Denní monitoring obsahuje {dailyArticleTarget} článků ze zdrojů českého, slovenského, polského, rakouského, německého, francouzského, amerického a širšího evropského medicínského prostředí. Veřejná a studentská úroveň je dostupná všem; odborné články pro lékaře a vědce se odemknou po uložení role a newsletteru.</p><div className="stats-strip" aria-label="Pokrytí kategorií">{specializations.map((item) => <span key={item}>{item}: 15+</span>)}</div><ArticleFilter />{results.length ? <div className="grid">{results.map((article) => { const access = resolveArticleAccess(article, profile); return <article className="card" key={article.id}><div className="meta"><span className="tag">{article.specialization}</span><span className="tag">{access.accessLabel}</span></div><h2>{article.title}</h2><p>{article.summary}</p><div className="meta"><span>{article.author}</span><span>{new Intl.DateTimeFormat("cs-CZ").format(new Date(article.date))}</span><span>{audienceLabels[article.audience]}</span><span>{article.sourceUrl ? <a href={article.sourceUrl} target="_blank" rel="noreferrer">{article.source}</a> : article.source}</span></div><Link className="button" href={`/articles/${article.slug}`}>Číst více / Read more</Link></article>; })}</div> : <div className="empty"><h2>Žádné články neodpovídají filtru.</h2><p>Zkuste zjednodušit vyhledávání nebo vybrat jinou specializaci, region či úroveň.</p><Link className="button" href="/articles">Zobrazit všechny články</Link></div>}</main>; }
