import type { CongressEventRow } from "@/types/database";
import { V21_MEDICAL_IMAGES } from "@/lib/v21/images";

/** Kurátorské kongresy — doplnění prázdné DB */
export const V21_CURATED_CONGRESSES: CongressEventRow[] = [
  {
    id: "curated-eular-2026",
    title: "EULAR Congress 2026",
    slug: "eular-congress-2026",
    summary:
      "Největší evropský kongres revmatologie — nové studie, guidelines a networking pro české revmatology.",
    body:
      "EULAR Congress představuje klíčové fórum pro prezentaci klinických studií, biologické léčby a AI v revmatologii. Česká delegace aktivně participuje na workshopech EULAR a ČLS JEP.",
    location: "Barcelona, Španělsko",
    venue: null,
    price_hint: null,
    source_url: "https://www.eular.org/",
    organizer: "EULAR",
    specialty: "Revmatologie",
    region: "EU",
    starts_at: "2026-06-10T08:00:00.000Z",
    ends_at: "2026-06-13T18:00:00.000Z",
    registration_url: "https://www.eular.org/",
    image_url: V21_MEDICAL_IMAGES.congress,
    published: true,
    featured: true,
    ai_extracted: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "curated-czech-rheum-2026",
    title: "Český revmatologický kongres 2026",
    slug: "cesky-revmatologicky-kongres-2026",
    summary:
      "Výroční sjezd České revmatologické společnosti — česká praxe, SÚKL, úhrady a kazuistiky.",
    body:
      "Tradiční odborná akce spojující klinickou praxi, legislativu úhrad a vzdělávání. Prezentace z Revmatologického ústavu a českých fakultních center.",
    location: "Praha, Česká republika",
    venue: null,
    price_hint: null,
    source_url: "https://www.cls.cz/",
    organizer: "ČLS JEP — Revmatologie",
    specialty: "Revmatologie",
    region: "CZ",
    starts_at: "2026-09-15T08:00:00.000Z",
    ends_at: "2026-09-17T17:00:00.000Z",
    registration_url: "https://www.cls.cz/",
    image_url: V21_MEDICAL_IMAGES.congress,
    published: true,
    featured: true,
    ai_extracted: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "curated-esmo-2026",
    title: "ESMO Congress 2026",
    slug: "esmo-congress-2026",
    summary: "Evropský kongres medicíny — onkologie, imunoterapie a multidisciplinární péče.",
    body:
      "Mezinárodní kongres s důrazem na evidence-based onkologii, klinické studie a implementaci do praxe. Relevantní pro internisty a onkology v ČR.",
    location: "Berlín, Německo",
    venue: null,
    price_hint: null,
    source_url: "https://www.esmo.org/",
    organizer: "ESMO",
    specialty: "Onkologie",
    region: "EU",
    starts_at: "2026-10-18T08:00:00.000Z",
    ends_at: "2026-10-22T18:00:00.000Z",
    registration_url: "https://www.esmo.org/",
    image_url: V21_MEDICAL_IMAGES.congress,
    published: true,
    featured: false,
    ai_extracted: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "curated-who-ehealth-2026",
    title: "WHO Global eHealth Symposium 2026",
    slug: "who-global-ehealth-2026",
    summary: "Globální sympozium WHO o digital health, interoperabilitě a AI v zdravotnictví.",
    body:
      "Prezentace strategií WHO, OECD a EU eHealth. Témata: telemedicína, bezpečnost dat, regulace AI ve zdravotnictví a česká národní eHealth strategie.",
    location: "Ženeva, Švýcarsko",
    venue: null,
    price_hint: null,
    source_url: "https://www.who.int/",
    organizer: "WHO",
    specialty: "Digitální zdravotnictví",
    region: "world",
    starts_at: "2026-11-05T09:00:00.000Z",
    ends_at: "2026-11-07T17:00:00.000Z",
    registration_url: "https://www.who.int/",
    image_url: V21_MEDICAL_IMAGES.digitalHealth,
    published: true,
    featured: false,
    ai_extracted: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "curated-lf-praha-2026",
    title: "Dny lékařské vědy UK Praha 2026",
    slug: "dny-lekarske-vedy-uk-praha-2026",
    summary: "Vědecké dny 1. LF UK — prezentace studentského a doktorského výzkumu.",
    body:
      "Akce pro studenty medicíny a young scientists. Sekce anatomie, fyziologie, patologie a klinických oborů. Inspirace pro studium medicíny v ČR.",
    location: "Praha, 1. LF UK",
    venue: null,
    price_hint: null,
    source_url: "https://www.lf1.cuni.cz/",
    organizer: "1. lékařská fakulta UK",
    specialty: "Studium medicíny",
    region: "CZ",
    starts_at: "2026-05-20T08:00:00.000Z",
    ends_at: "2026-05-22T16:00:00.000Z",
    registration_url: "https://www.lf1.cuni.cz/",
    image_url: V21_MEDICAL_IMAGES.university,
    published: true,
    featured: true,
    ai_extracted: null,
    created_at: new Date().toISOString(),
  },
];

export function getCuratedCongressBySlug(slug: string): CongressEventRow | null {
  return V21_CURATED_CONGRESSES.find((c) => c.slug === slug) ?? null;
}
