-- Sample B2B Tržiště organizations + listings so production is not an empty catalog.
-- Idempotent. Does not overwrite operator-created rows.

INSERT INTO public.exchange_organizations (
  id, slug, legal_name, trade_name, kind, registration_id, vat_id, country_code, website,
  contact_email, contact_phone, contact_person, availability_regions, verified, plan,
  source_locale, description, microsite_enabled, api_import_enabled, ad_credits
) VALUES
  (
    '11111111-1111-4111-8111-111111111111',
    'nordic-diagnostics',
    'Nordic Diagnostics GmbH',
    'Nordic Diagnostics',
    'company',
    'HRB 184920',
    'DE813492001',
    'DE',
    'https://medscopeglobal.com/exchange',
    'partners@medscopeglobal.com',
    '+49 30 000000',
    'Dr. Lena Hartmann',
    ARRAY['EU']::public.exchange_availability_region[],
    true,
    'pro',
    'de',
    'IVD and point-of-care diagnostics for hospital laboratories. CE-marked devices, B2B supply only.',
    false,
    false,
    0
  ),
  (
    '22222222-2222-4222-8222-222222222222',
    'pacific-lab-network',
    'Pacific Lab Network Pte. Ltd.',
    'Pacific Lab Network',
    'laboratory',
    '201938472K',
    NULL,
    'SG',
    'https://medscopeglobal.com/exchange',
    'labs@medscopeglobal.com',
    NULL,
    'Wei Tan',
    ARRAY['Asia', 'Global']::public.exchange_availability_region[],
    true,
    'enterprise',
    'en',
    'Reference laboratory network offering specialty assays and clinical-trial sample logistics across Asia.',
    true,
    true,
    8
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'university-hospital-morava',
    'Fakultní nemocnice Morava, p.o.',
    'FN Morava',
    'hospital',
    '00843989',
    NULL,
    'CZ',
    NULL,
    'procurement@medscopeglobal.com',
    NULL,
    'Ing. Petra Nováková',
    ARRAY['EU']::public.exchange_availability_region[],
    true,
    'basic',
    'cs',
    'Tertiary hospital procurement and investigator-initiated research partnerships.',
    false,
    false,
    0
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.exchange_listings (
  id, slug, kind, status, organization_id, category, source_locale, title, summary, description,
  availability_region, availability_regions, certifications, certification_not_applicable,
  price_hint, currency, featured, image_url
) VALUES
  (
    'aaaaaaa1-1111-4111-8111-111111111111',
    'ce-poc-immunoassay-analyzer',
    'product',
    'approved',
    '11111111-1111-4111-8111-111111111111',
    'diagnostics',
    'en',
    'CE-marked POC immunoassay analyzer',
    'Hospital-grade point-of-care immunoassay platform with EU MDR documentation pack.',
    'Compact immunoassay analyzer for emergency and outpatient labs. Supplied B2B with CE technical file, ISO 13485 QMS and installation training. Direct contract with the manufacturer — MedScopeGlobal only introduces the parties.',
    'EU',
    ARRAY['EU']::public.exchange_availability_region[],
    ARRAY['CE', 'ISO'],
    false,
    'B2B on request',
    'EUR',
    true,
    '/assets/marketing/exchange/diagnostics.webp'
  ),
  (
    'aaaaaaa2-2222-4222-8222-222222222222',
    'asia-specialty-lab-panel',
    'service',
    'approved',
    '22222222-2222-4222-8222-222222222222',
    'lab-analysis',
    'en',
    'Specialty immunology panels for Asia-Pacific trials',
    'Central-lab immunology and biomarker panels with chain-of-custody across APAC sites.',
    'Reference-lab service for sponsors running multi-country trials in Asia. Includes sample logistics, validated assays and bilingual reports. Not a consumer lab and not a public test marketplace.',
    'Asia',
    ARRAY['Asia', 'Global']::public.exchange_availability_region[],
    ARRAY['ISO'],
    false,
    'Per panel / protocol',
    NULL,
    true,
    '/assets/marketing/exchange/laboratories.webp'
  ),
  (
    'aaaaaaa3-3333-4333-8333-333333333333',
    'hospital-ultrasound-rfp-eu',
    'demand',
    'approved',
    '33333333-3333-4333-8333-333333333333',
    'procurement',
    'cs',
    'Poptávka: 4 prenatální ultrazvukové systémy (EU)',
    'Fakultní nemocnice hledá CE dodavatele čtyř prenatálních UZ systémů včetně servisu.',
    'Poptávka je určena pouze B2B dodavatelům se statusem CE a servisní sítí v EU. Nemocnice uzavírá smlouvu přímo. MedScopeGlobal nezpracovává platbu ani dodání.',
    'EU',
    ARRAY['EU']::public.exchange_availability_region[],
    ARRAY['CE'],
    false,
    NULL,
    NULL,
    false,
    '/assets/marketing/exchange/hospitals.webp'
  ),
  (
    'aaaaaaa4-4444-4333-8333-444444444444',
    'telemedicine-oncology-second-opinion',
    'service',
    'approved',
    '11111111-1111-4111-8111-111111111111',
    'telemedicine',
    'en',
    'Oncology second-opinion network for hospitals',
    'Institution-to-institution tumor-board second opinions. No direct-to-patient care.',
    'B2B telemedicine for hospitals and cancer centers. Cases stay inside the requesting institution’s record. Marketplace contact is the only MedScopeGlobal involvement.',
    'Global',
    ARRAY['Global']::public.exchange_availability_region[],
    ARRAY['ISO'],
    false,
    NULL,
    NULL,
    false,
    '/assets/marketing/exchange/telemedicine.webp'
  )
ON CONFLICT (slug) DO NOTHING;
